### PR TITLE
Added dish counter and bag sprite

### PR DESCRIPTION
**Pull request by RichaMaurya21**
Added dish counter and bag sprite

### CODE REVIEW

**Comment by Guinguin0416** [comment]
There are few bugs I noticed when playing:
1) the dish counter sprite is overlapping with the red diamond 50-50 power-up on the top of the screen
2) when increasing the dishcounter, the quantity of each ingredient did not decrease accordingly
3) the coin balance are negative inside the sanctum (might have to pull the latest change on main, Nicky already fixed this issue yesterday)

Would like to have more insights on this version @devangsharma14 @SanBlig

**Comment by devangsharma14** [comment]
Let us merge this PR now and work on the bugs on the next iterations. @RichaMaurya21 @Guinguin0416

**Comment by RichaMaurya21** [comment]
1)Changed dish sprite position. (Updated as per my laptop's resolution let me know if still unaligned)
2)Implemented dish counter as the quantity of each ingredient will decrease accordingly.
3)Implemented sanctum logic for coin and ingredient counter according to the recipes cooked

Please review! @devangsharma14  @Guinguin0416

**Comment by Guinguin0416** [comment]
Works well on my end, if any other bugs occur, fix them as we go

**Pull request merged**
