### PR TITLE
Add Animation for counters

### PR DESCRIPTION
**Pull request by tommyshang**
FadeTextToFullAlpha Animation for counters.
Obstacle2 still has the overlapping issue.

### CODE REVIEW

**Comment by SanBlig** [comment]
1. The numbers are not aligned with the ingredient icons.
2. The dish counter shows animation but it is set to 0 even after I have created a dish.
3. (Optional) would have been nice if even the coins counter had animation.

**Comment by synickyw4869** [comment]
I also just tested --
1. The numbers align with the ingredient icons on any aspect that is not free aspect or 16:10 one
2. Dish counter is also a problem for me.

**Comment by synickyw4869** [comment]
works for me!

**Comment by SanBlig** [comment]
Looks great!

**Comment by SanBlig** [comment]
@tommyshang Could you pull latest changes from main (including Nicky's UI changes) and add your changes on top of it? Also, could you remove the counters on the top left of the game screen? This might help to resolve merge conflicts.

**Pull request closed without merging**
