### PR TITLE
Fixed two bugs in level 1

### PR DESCRIPTION
**Pull request by vedikaya**
Added logic for below :
1. On Level Restart, reset the ingredient counters.
2. Remove -2 coins for sanctum/cooking station entrance.

### CODE REVIEW

**Comment by vedikaya** [comment]
@devangsharma14  and @Guinguin0416  please review the changes and let me know if any changes are required.

**Review by devangsharma14 — APPROVED** [review]
Looks good to me!

**Comment by SanBlig** [comment]
Hi @devangsharma14 , can we keep this PR pending? @Guinguin0416 will be created a new PR for level 2 and 3 changes, we can merge this after that as these changes are not compatible with the level 2 and 3 changes.

**Comment by devangsharma14** [comment]
Sounds good!

**Comment by vedikaya** [comment]
Reviewed PR#65 looks good to me. @sbaliga@usc.edu and @jiayupu@usc.edu we can merge PR#65 and discard #63.
Will submit a new PR for my other changes.

**Pull request closed without merging**
