### PR TITLE
Add Hint Counter + Fix Power-up Spawn Logic

### PR DESCRIPTION
**Pull request by devangsharma14**

### CODE REVIEW

**Comment by Guinguin0416** [comment]
hey I noticed few minor things:
1) hint counter was not reset after restart/die/exit
2) the hint counter inside the santum is a school bag, i think it would be better to keep it consistent as a clipboard

**Comment by devangsharma14** [comment]
Fixes Done

**Comment by SanBlig** [comment]
1. Collect powerups > Pause > Exit > Start another Level > Powerup counter is not reset
2. Time is fast in the sanctum
3. Bag icon still present in sanctum

**Comment by devangsharma14** [comment]
Fixes Pushed

**Comment by Guinguin0416** [comment]
looks good!

**Pull request merged**
