### PR TITLE
add arrow for each target

### PR DESCRIPTION
**Pull request by JiangyunWang**
Add the diamond on each new object on the tutorial and change the keyboard instruction

https://user-images.githubusercontent.com/36421739/203744031-df3596fc-f850-4cd5-b1f7-94a107670f57.mov

### CODE REVIEW

**Comment by Guinguin0416** [comment]
Works well on my end! The only concern I have is the spawning order/frequency. For now it seems we only have trashcan at the very beginning, and then spawn hammer, and then power-up. When the player collects the hammer, they have no chance to actually use on an obstacle.

**Comment by JiangyunWang** [comment]
add bin in the hammer part
Screen Shot 2022-11-24 at 10 53 11 AM

**Comment by SanBlig** [comment]
I think the spawning logic should remain the same for all the things. Right now I can only see trash cans for a very long time, then hammer+trash can, but it goes on for very long and I run out of time in the tutorial. Could you please revert to the previous spawning logic? The keys in the beginning and the arrow on top of objects looks good!

**Comment by devangsharma14** [comment]
I will work on the changes

**Comment by JiangyunWang** [comment]
Losing lift effect

https://user-images.githubusercontent.com/36421739/204066328-7b3ca012-c6fe-4054-8510-de8395adcfb8.mov

**Pull request closed without merging**
