### PR TITLE
Level wise obstacles and changes in spawning logic 

### PR DESCRIPTION
**Pull request by atharvaagwekar**

### CODE REVIEW

**Comment by SanBlig** [comment]
For the powerups, is it possible to disable collecting them if the player already has one powerup of the same type? (That is, player will just pass through the prefab)
Apart from that, looks good to me!

**Comment by gods-righteous-man** [comment]
**Fixed**



> For the powerups, is it possible to disable collecting them if the player already has one powerup of the same type? (That is, player will just pass through the prefab) Apart from that, looks good to me!

**Comment by SanBlig** [comment]
In tutorial I am not able to collect even one hint or 50-50. Looks good in the game levels.

**Comment by atharvaagwekar** [comment]
> In tutorial I am not able to collect even one hint or 50-50. Looks good in the game levels.

Fixed

**Comment by SanBlig** [comment]
Looks good to me!

**Review by SanBlig — APPROVED** [review]

**Comment by Guinguin0416** [comment]
looks good to me!

**Pull request merged**
