### PR TITLE
Cooking Station Added

### PR DESCRIPTION
**Pull request by synickyw4869**
TODO:
- When player collides/collects ingredient increment its counter and deduct $2 from balance.
- Remove Hammer and Time power-up from this level
- Spawn Cooking Station Game object (choose appropriate 3d material) after every 20 sec.
- Cooking Stations should only be spawned if player has a complete set of the 3 ingredients
- On colliding with the Cooking Station open Sanctum

### CODE REVIEW

**Comment by Guinguin0416** [comment]
For some reason, I was not able to open the project. It gave me the error: The project you are opening cotains compilation erros. Does this happen to you? @devangsharma14 @tommyshang

**Comment by Guinguin0416** [comment]
works well on my end

**Comment by devangsharma14** [comment]
I couldn't collect ingredients: The player was running through it without collecting anything during one of the gameplay. But after restarting it worked. 
However, I think this is good to merge. We can fix the bugs incrementally.

**Comment by devangsharma14** [comment]
Let us merge this!
And fix bugs iteratively.

**Pull request merged**
